<br>
# Numerical Python (NumPy)
NumPy is the fundamental package for scientific computing with Python. It contains among other things:

- a powerful N-dimensional array object
- sophisticated (broadcasting) functions
- implements all the heavy lifting in C language which is much faster.
- useful linear algebra, Fourier transform, and random number capabilities
- Besides its obvious scientific uses, NumPy can also be used as an efficient multi-dimensional container of generic data. 
- Arbitrary data-types can be defined. This allows NumPy to seamlessly and speedily integrate with a wide variety of databases.


# ndarray object
The ndarray (pronounced N D array) object is the main object for representing your array. This object can handle multi-dimensional array of any size that your memory can store. The biggest differences between a Python list and a ndarray object are these:

- ndarray is a fixed size array while list has a dynamic size. When you reshare a ndarray a new object is created with the new shape and the old object is deleted from memory.
- ndarray allows mathematical and logical operations on complete multi-dimensional arrays. With a Python list you will have to iterate over the sequence which take more time and code.
 
- ndarray has homogeneous data type for the complete array while Python list can contain multiple data types within a single array.


http://www.numpy.org/


In [69]:
import numpy as np

<br>
## Creating and initialize Arrays

Create a list and convert it to a numpy array

In [70]:
my_list = [1, 2, 3,4,5]
x = np.array(my_list)
x

array([1, 2, 3, 4, 5])

<br>
pass list directly

In [71]:
array_1 = np.array([6, 7, 8, 9])
array_1

array([6, 7, 8, 9])

<br>
list of lists to create a multidimensional array.

In [72]:
array_2 = np.array([[7, 8, 9], [10, 11, 12]])
array_2

array([[ 7,  8,  9],
       [10, 11, 12]])

<br>
create with `arange` type.

In [73]:
array_3 = np.arange(0, 30, 2) # start at 0 stop before 30 with steps of 2
array_3

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

<br>
`linspace` create array evenly spaced numbers over a specified interval.

In [74]:
array_4 = np.linspace(0, 3, 9) # return 9 evenly spaced values from 0 to 3
array_4

array([ 0.   ,  0.375,  0.75 ,  1.125,  1.5  ,  1.875,  2.25 ,  2.625,  3.   ])

<br>
- shape method return the dimensions of the array. (rows, columns)
- dtype method return the type
- ndim return number of diminsion 
- size return array size

In [75]:
print(array_1)
print(array_2)


print(array_1.shape)
print(array_2.shape)

print(array_1.dtype)

print(array_1.ndim)
print(array_2.ndim)

print(array_1.size)
print(array_1.size * array_1.itemsize, "bytes") 

[6 7 8 9]
[[ 7  8  9]
 [10 11 12]]
(4,)
(2, 3)
int32
1
2
4
16 bytes


<br>
`reshape` returns an array with the same data with a new shape. new diminsion must match old diminsion 

In [76]:
array_3 = np.arange(0, 30, 2) # start at 0 stop before 30 with steps of 2
print (array_3)
array_3 = array_3.reshape(3, 5) # reshape array to be 3x5
array_3

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28]


array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

<br>
`resize` changes the shape and size of array in-place. new diminsion must match old diminsion 

In [77]:
array_4 = np.linspace(0, 3, 9) # return 9 evenly spaced values from 0 to 3
print(array_4)
array_4.resize(3, 3)
array_4

[ 0.     0.375  0.75   1.125  1.5    1.875  2.25   2.625  3.   ]


array([[ 0.   ,  0.375,  0.75 ],
       [ 1.125,  1.5  ,  1.875],
       [ 2.25 ,  2.625,  3.   ]])

<br>
`ones` creates a new array of given shape and type, filled with ones.

In [78]:
np.ones((3, 2))

array([[ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.]])

<br>
`zeros` creates a new array of given shape and type, filled with zeros.

In [79]:
np.zeros((2, 3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

<br>
`eye` creates a 2-D array with ones on the diagonal and zeros elsewhere.

In [80]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

<br>
`diag` extracts a diagonal  array.

In [81]:
np.diag(array_4)

array([ 0. ,  1.5,  3. ])

<br>
Create an array using repeating list (or see `np.tile`)

In [82]:
np.array([1, 2, 3] * 4)

array([1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

<br>
create array and repeat elements n times .

In [83]:
np.repeat([1, 2, 3], 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

<br>
## Operations

Use `+`, `-`, `*`, `/` and `**` to perform element wise addition, subtraction, multiplication, division and power.

In [84]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
print (x)
print (y)

[1 2 3]
[4 5 6]


In [85]:
print(x + 1) # elementwise constant addition     [1 2 3] + 1 = [2 3  4]
print(x / 3) # elementwise constant addition     [1 2 3] / 3 = [0.33333333  0.66666667  1. ]

[2 3 4]
[ 0.33333333  0.66666667  1.        ]


In [86]:
print(x + y) # elementwise addition     [1 2 3] + [4 5 6] = [5  7  9]
print(x - y) # elementwise subtraction  [1 2 3] - [4 5 6] = [-3 -3 -3]

[5 7 9]
[-3 -3 -3]


In [87]:
print(x * y) # elementwise multiplication  [1 2 3] * [4 5 6] = [4  10  18]
print(x / y) # elementwise divison         [1 2 3] / [4 5 6] = [0.25  0.4  0.5]

[ 4 10 18]
[ 0.25  0.4   0.5 ]


In [88]:
print(x**2) # elementwise power  [1 2 3] ^2 =  [1 4 9]

[1 4 9]


## Odd or even

In [89]:
print (array_1)
array_1 % 2 == 0

[6 7 8 9]


array([ True, False,  True, False], dtype=bool)

<br>
**Dot Product:**  
np.dot 

For 2-D arrays it is equivalent to matrix multiplication, and for 1-D
    arrays to inner product of vectors:
    
$ \begin{bmatrix}x_1 \ x_2 \ x_3\end{bmatrix}
\cdot
\begin{bmatrix}y_1 \\ y_2 \\ y_3\end{bmatrix}
= x_1 y_1 + x_2 y_2 + x_3 y_3$

In [90]:
x.dot(y) # dot product  1*4 + 2*5 + 3*6

32

In [91]:
A = np.random.randint(1,10,(3,3))
B = np.random.randint(1,10,(3,3))
print("A:\n==")
print(A)
print("B:\n==")
print(B)

A:
==
[[4 6 5]
 [9 8 8]
 [5 4 6]]
B:
==
[[7 5 3]
 [4 8 9]
 [3 2 1]]


In [92]:
C = A.dot(B)
print(C)

[[ 67  78  71]
 [119 125 107]
 [ 69  69  57]]


<br>
## Math Functions

Numpy has many built in math functions that can be performed on arrays.

In [93]:
z = np.array([-2, -2, -2, 3, 3])

In [94]:
z.sum()

0

In [95]:
z.max()

3

In [96]:
z.min()

-2

In [97]:
z.mean()

0.0

In [98]:
z.std()

2.4494897427831779

<br>
`argmax` and `argmin` return the index of the maximum and minimum values in the array.

In [99]:
z.argmax()

3

In [100]:
z.argmin()

0

<br>
## Indexing / Slicing
Remember that indexing starts at 0.

### 1D Indexing

In [101]:
array_1 = np.array(range(5000000))
array_1

array([      0,       1,       2, ..., 4999997, 4999998, 4999999])

In [102]:
array_1[-1]

4999999

In [103]:
array_1[1:10]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [104]:
array_1[1:10:2]

array([1, 3, 5, 7, 9])

### 2D Indexing

In [105]:
list_1 = [[i+l for l in range(2000)] for i in range(2000)]
array_1 = np.array(list_1)
array_1

array([[   0,    1,    2, ..., 1997, 1998, 1999],
       [   1,    2,    3, ..., 1998, 1999, 2000],
       [   2,    3,    4, ..., 1999, 2000, 2001],
       ..., 
       [1997, 1998, 1999, ..., 3994, 3995, 3996],
       [1998, 1999, 2000, ..., 3995, 3996, 3997],
       [1999, 2000, 2001, ..., 3996, 3997, 3998]])

In [106]:
array_1[2]

array([   2,    3,    4, ..., 1999, 2000, 2001])

In [107]:
array_1[2][0]

2

In [108]:
array_1[2,0]

2

In [109]:
array_1[1:5,0]

array([1, 2, 3, 4])

### filtering

In [110]:
array_1 = np.array(range(10))
print(array_1)

[0 1 2 3 4 5 6 7 8 9]


In [111]:
mask = np.array([True, False, False, False, False, False, False, False, False, True])
print(array_1[mask])

[0 9]


In [112]:
array_1[array_1 < 5]

array([0, 1, 2, 3, 4])

In [113]:
array_1[array_1 % 2 == 0]

array([0, 2, 4, 6, 8])

### To apply a function to a numpy array, you have to vectorize the function.

In [114]:
def isodd(n):
    return bool(n % 2)

visodd = np.vectorize(isodd)

In [115]:
array_1[visodd(array_1)]

array([1, 3, 5, 7, 9])

<br>
## Copying Data

Be careful with copying and modifying arrays in NumPy!


In [116]:
x = np.arange(36)
x.resize((6, 6))
print (x)
y = x[:3,:3]
y

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]])

<br>
Set this slice's values to zero ([:] selects the entire array)

In [117]:
y[:] = 0
y

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

<br>
`x` has also been changed!

In [118]:
x

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

<br>
To avoid this, use `x.copy` to create a copy that will not affect the original array

In [119]:
x_copy = x.copy()
x_copy

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

<br>
Now when x_copy is modified, x will not be changed.

In [120]:
x_copy[:] = 10
print(x_copy, '\n')
print(x)

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]] 

[[ 0  0  0  3  4  5]
 [ 0  0  0  9 10 11]
 [ 0  0  0 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


<br>
### Iterating Over Arrays

Let's create a new 4 by 3 array of random numbers 0-9.

In [121]:
x = np.random.randint(0, 10, (4,3))
x

array([[8, 3, 3],
       [1, 0, 2],
       [6, 0, 9],
       [6, 5, 1]])

<br>
Iterate by row:

In [122]:
for row in x:
    print(row)

[8 3 3]
[1 0 2]
[6 0 9]
[6 5 1]


<br>
Iterate by index:

In [123]:
for i in range(len(x)):
    print(x[i])

[8 3 3]
[1 0 2]
[6 0 9]
[6 5 1]


<br>
Iterate by row and index:

In [124]:
for i, row in enumerate(x):
    print('row', i, 'is', row)

row 0 is [8 3 3]
row 1 is [1 0 2]
row 2 is [6 0 9]
row 3 is [6 5 1]


<br>
Use `zip` to iterate over multiple iterables.

In [125]:
y = x**2
y

array([[64,  9,  9],
       [ 1,  0,  4],
       [36,  0, 81],
       [36, 25,  1]], dtype=int32)

In [126]:
for i, j in zip(x, y):
    print(i,'+',j,'=',i+j)

[8 3 3] + [64  9  9] = [72 12 12]
[1 0 2] + [1 0 4] = [2 0 6]
[6 0 9] + [36  0 81] = [42  0 90]
[6 5 1] + [36 25  1] = [42 30  2]


# References:
    
- https://docs.scipy.org/doc/numpy-dev/user/quickstart.html
- https://docs.scipy.org/doc/numpy-1.13.0/reference/
- http://matplotlib.org/